# Generated by Django 4.2.5 on 2025-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_add_initial_movies_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
